

// TOOL:     vlog2tf
// DATE:     11/13/07  14:05:45 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   top
// DESIGN:   top
// FILENAME: top.tft
// PROJECT:  osctimer
// VERSION:  1.0
// This file is auto generated by the ispLEVER


`timescale 1 ns / 10 ps

// Define Module for Test Fixture
module osc_pg_tf();

// Inputs
    reg in0;
    reg in1;
    reg rst;
    reg tmr_rst;
    reg osc_dis0;
    reg osc_dis1;
    reg [3:0] DX;
    reg Enable;


// Outputs
    wire out0;
    wire out1;
    wire [3:0] QX;
  integer i = 0;


// Bidirs


// Instantiate the UUT
    osc_pg_vlog UUT (
        .in0(in0), 
        .in1(in1), 
        .rst(rst), 
        .tmr_rst(tmr_rst), 
        .osc_dis0(osc_dis0), 
        .osc_dis1(osc_dis1), 
        .out0(out0), 
        .out1(out1), 
        .DX(DX), 
        .Enable(Enable), 
        .QX(QX)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            in0 = 0;
            in1 = 0;
            rst = 0;
            tmr_rst = 0;
            osc_dis0 = 0;
            osc_dis1 = 0;
            DX = 0;
            Enable = 0;
    end

  initial begin   // 'Enable'
    #1000 Enable = 0;
    #10000 Enable = 1;
    #60000 Enable = 0;
    #2500 Enable = 0;
  end  // Enable

 
  initial begin   // 'rst'
    #0   rst = 0;
    #7003   rst = 1;
    #2000 rst = 0;
    #100000 rst = 0;
  end  // rst

  initial begin   // 'tmr_rst'
    #0   tmr_rst = 1;
    #4007  tmr_rst = 1;
    #2300 tmr_rst = 0;
    #100000 tmr_rst = 0;
  end  // tmr_rst

  initial begin   // 'osc_dis0'
    #0   osc_dis0 = 1;
    #4027  osc_dis0 = 1;
    #1500 osc_dis0 = 0;
    #100000 osc_dis0 = 0;
  end  // osc_dis0
  initial begin   // 'osc_dis1'
    #0   osc_dis1 = 1;
    #4036  osc_dis1 = 1;
    #1800 osc_dis1 = 0;
    #100000 osc_dis1 = 0;
  end  // osc_dis1
  initial begin   // 'in0'
	for (i=0; i<1000; i=i+1)
    #2909   in0 = ~in0;
  end  // in0

  initial begin   // 'in1'
	for (i=0; i<1000; i=i+1)
    #2260   in1 = ~in1;
  end  // in1

  initial begin   // 'DX'
	for (i=0; i<200; i=i+1)
    #3007   DX = DX + 1;
  end  // DX


endmodule // tb_osc_pg
